export * from "./Services/IHttpService";
export * from "./Services/ICrudService";
export * from "./Services/ICreatableService";
export * from "./Services/IDeletableService";
export * from "./Services/IListableService";
export * from "./Services/IReadableService";
export * from "./Services/ISearchableService";
export * from "./Services/ISimpleCrudService";
export * from "./Services/IUpdatableService";